### ISSUE TITLE
Doesn't work with OIDs with subidentifier > 255

### ISSUE THREAD

**Issue by metaathron** [patricklaf/SNMP#3]
For most enterprise OIDs (1.3.6.1.4.1.xxx) it doesn't work. It gives value mod 255.
It's necessary to declare `subidentifier` as `uint32_t` in `ObjectIdentifierBER::decode` and `ObjectIdentifierBER::encode`.
Then it will behave correctly for decoding, but not for encoding where length is calculated incorrectly. My messy solution for now is: 

    const uint32_t ObjectIdentifierBER::encode(unsigned char *buffer) {
    uint32_t index = 0;
    uint32_t subidentifier = 0;
    unsigned char *pointer = buffer;
    unsigned char *lenpointer = buffer+1;
    // T, L
    *pointer++ = _type;
    *pointer++ = _length;
    // V
    char *token = (char*) _value;
    while (token != NULL) {
        switch (index) {
        case 0:
            subidentifier = atol(token);
            break;
        case 1:
            subidentifier = subidentifier * 40 + atoi(++token);
            *pointer = subidentifier;
            break;
        default: {
            subidentifier = atol(++token);
            uint32_t value = subidentifier;
            uint32_t length = 0;
            do {
                value >>= 7;
                length++;
            } while (value);
            pointer += length;
            value = subidentifier;
            for (uint32_t index = 0; index < length; ++index) {
                *pointer-- = (value & 0x7F) | (index ? 0x80 : 0x00);
                value >>= 7;
            }
            pointer += length;
        }
            break;
        }
        token = strchr(token, '.');
        index++;
    }
	_size = pointer - buffer + 1;
	_length = _size - 2;
	*lenpointer = _length;
    return _size;
    }

**Comment by patricklaf** [comment]
Hello @metaathron ,
Thanks for pointing this out.

I think that it's enough to change the type of `subidentifier` to `uint32_t`. No need to use `lenpointer` the way you do.

I tried this code:

```cpp
#include "Arduino.h"

#include "SNMP.h"
#include "Toolbox.h" // Hexa object

Hexa hexa(Serial); // Dump 

uint8_t buffer[64];

void setup() {
	Serial.begin(115200);
	SNMP::ObjectIdentifierBER oid("1.3.6.1.2.1.2.2.1.8.4096");
	memset(buffer, 0xFF, 64);
	oid.encode(buffer);
	hexa.dump(buffer,64);
}

void loop() {
}
```

With current library, it produces this output:

```
00000000  06 0B 2B 06 01 02 01 02  02 01 08 00 FF FF FF FF  . . + . . . . .  . . . . . . . .
```

Subidentifier is not correctly encoded but length = 0B is OK.

With `subidentifier` type changed to `uint32_t`, I get this:

```
00000000  06 0B 2B 06 01 02 01 02  02 01 08 A0 00 FF FF FF  . . + . . . . .  . . . . . . . .
```

That seems correct.
Let me know what do you think about it.

**Comment by metaathron** [comment]
It doesn't behave the same way for me.
There was more to do. `sprintf` shall use `%lu` and `atoi` shall be replaced with `atol` to make it decode and encode longs properly and then it returns incorrect length.
I was testing with OID 1.3.6.1.4.1.54858.81.1.1.1.0
request: 
`... 06 0b 2b 06 01 04 01 83 ac 4a 51 04 00 05 00`

response:
`... 06 0d 2b 06 01 04 01 83 ac 4a 51 04 00 00 00 02 01 00`

**Comment by patricklaf** [comment]
What platform and card are you using?
I wrote the quick test for Arduino Mega.
Once again, a platform dependent problem.

**Comment by metaathron** [comment]
Arduino Mega 2560 programmed via Arduino IDE 2.2.1
It breaks after 32767 (which is maximum value of signed int16. Until this value it works correctly.

**Comment by metaathron** [comment]
It's necessary to change `atoi` to `atol` in `ObjectIdentifierBER::setValue` and `ObjectIdentifierBER::encode` and `%d` to `%lu` in `ObjectIdentifierBER::decode` Then it will work flawlessly even for large numbers.

**Comment by patricklaf** [comment]
I just created a PR #4.
Can you have a look and let me know if it works fine.
I need to check with STM32 platform before merging.

**Comment by metaathron** [comment]
Seems to be working well.

**Comment by patricklaf** [comment]
OK. Thanks.

**Comment by patricklaf** [comment]
PR #4 merged.
Issue solved.
@metaathron , thanks for your help.
